# mediawiki-mariadb-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediawiki-mariadb-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mediawiki-mariadb-chart.name" . }}
    helm.sh/chart: {{ include "mediawiki-mariadb-chart.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mediawiki-mariadb-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mediawiki-mariadb-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mediawiki.image.repository }}:{{ .Values.mediawiki.image.tag }}"
          ports:
            - name: http
              containerPort: 80
