# mediawiki-mariadb-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mediawiki.name }}
spec:
  replicas: {{ .Values.mediawiki.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mediawiki.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mediawiki.name }}
    spec:
      volumes:
        - name: tmpdir
          emptyDir: { }
      containers:
        - name: {{ .Values.mediawiki.container.name }}
          image: {{ .Values.mediawiki.container.image.repository }}:{{ .Values.mediawiki.container.image.tag }}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: tmpdir
              mountPath: /tmp  # Corrected the escape character
          resources:
            requests:
              cpu: {{ .Values.mediawiki.container.requests.cpu | quote }}
              memory: {{ .Values.mediawiki.container.requests.memory | quote }}
            limits:
              cpu: {{ .Values.mediawiki.container.limits.cpu | quote }}
              memory: {{ .Values.mediawiki.container.limits.memory | quote }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MEDIAWIKI_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mediawiki.secret.name | quote }}
                  key: MEDIAWIKI_DATABASE_PASSWORD                  

        - name: {{ .Values.mariadb.container.name }}
          image: {{ .Values.mariadb.container.image.repository }}:{{ .Values.mariadb.container.image.tag }}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: tmpdir
              mountPath: /tmp  # Corrected the escape character
          resources:
            requests:
              cpu: {{ .Values.mariadb.container.requests.cpu | quote }}
              memory: {{ .Values.mariadb.container.requests.memory | quote }}
            limits:
              cpu: {{ .Values.mariadb.container.limits.cpu | quote }}
              memory: {{ .Values.mariadb.container.limits.memory | quote }}  
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secret.name }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secret.name }}
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306