# mediawiki-mariadb-chart/templates/mariadb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki-mariadb-chart.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "mediawiki-mariadb-chart.name" . }}
    helm.sh/chart: {{ include "mediawiki-mariadb-chart.chart" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mediawiki-mariadb-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
