# mediawiki-mariadb-chart/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediawiki-mariadb-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mediawiki-mariadb-chart.name" . }}
    helm.sh/chart: {{ include "mediawiki-mariadb-chart.chart" . }}
type: Opaque
data:
  mariadb-root-password: {{ .Files.Get "files/mariadb-root-password" | b64enc | quote }}
  mariadb-password: {{ .Files.Get "files/mariadb-password" | b64enc | quote }}
