# mediawiki-mariadb-chart/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mediawiki.secret.name }}
type: Opaque
data:
  MEDIAWIKI_DATABASE_PASSWORD: {{ .Values.mediawiki.secret.data.password | b64enc }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.secret.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.secret.data.rootPassword | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mariadb.secret.data.password | b64enc }}